=== Mouad-elkbabty/G/Profil/profil.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux" 
           targetNamespace="http://myGame/tux"
           elementFormDefault="qualified">
    
<xs:include schemaLocation="dico.xsd"/>

   <!-- Racine : profil -->
    <xs:element name="profil" type="tux:Profil"/>
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="avatar" type="xs:string"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="tux:Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- Type : Parties -->
    <xs:complexType name="Parties">
        <xs:sequence>
          <xs:element name="partie" type="tux:Partie" maxOccurs="unbounded" />
        </xs:sequence> 
    </xs:complexType>
    
    
    <!-- Type : Partie -->
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" type="tux:Temps"/>
            <xs:element name="niveau" type="tux:Niveau" />
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
        <xs:attribute name="trouvÃ©" type="xs:string" use="optional"/> 
    </xs:complexType>
    
    
     <!-- Type : Temps -->
    <xs:simpleType name="Temps">
        <xs:restriction base="xs:double">
             <xs:minInclusive value='0.0'/>
        </xs:restriction>
    </xs:simpleType>
    
    
</xs:schema>

=== Mouad-elkbabty/G/Profil/profil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / Céline Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->

<tux:profil
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:tux='http://myGame/tux'
    xsi:schemaLocation='http://myGame/tux ../xsd/profil.xsd'>
    
    <tux:nom>Quentin</tux:nom>
    <tux:avatar>kratos.jpg</tux:avatar>
    <tux:anniversaire>2002-11-11</tux:anniversaire>
    <tux:parties>
        <tux:partie date="2022-10-03" trouvé="20%">
            <tux:temps>30.0</tux:temps>
            <tux:niveau niv="2">
                <tux:mot>tigre</tux:mot>
            </tux:niveau>
        </tux:partie>
        <tux:partie date="2022-12-03" trouvé="100%">
            <tux:temps>36.0</tux:temps>
            <tux:niveau niv="2">
                <tux:mot>oncle</tux:mot>
            </tux:niveau>
        </tux:partie>
    </tux:parties>

</tux:profil>
