=== Mouad-elkbabty/G/xsd/dico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0 "
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dico="http://myGame/tux"
           targetNamespace="http://myGame/tux"
           elementFormDefault="qualified">
    
    
    <!-- Racine : dictionnaire -->
    <xs:element name="dictionnaire" type="dico:Dictionnaire"/>
    
    
    <!-- Type : Dictionnaire -->
    <xs:complexType name = "Dictionnaire">
        <xs:sequence>
            <xs:element name="niveaux"  type="dico:Niveaux"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- Type : Niveaux -->
    <xs:complexType name="Niveaux">
        <xs:sequence>
            <xs:element maxOccurs="5" name="niveau" type="dico:Niveau"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- Type : Niveau -->
    <xs:complexType name="Niveau">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="mot" type="dico:Mot"/>
        </xs:sequence>
        <xs:attribute name="niv" type="dico:Niv" use="required"/>
    </xs:complexType>
    
    
    <!-- Type : Niv -->
    <xs:simpleType name="Niv">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!-- Type : Mot  -->
    <xs:simpleType name="Mot">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Zéàèùç\-])+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Mouad-elkbabty/G/xml/dico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<dictionnaire
                xmlns="http://myGame/tux"
                xsi:schemaLocation="http://myGame/tux ../xsd/dico.xsd"
                xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance">
<niveaux>            
        <niveau niv='1'>
            <mot>main</mot>
            <mot>maman</mot>
            <mot>papa</mot>
            <mot>nez</mot>
            <mot>jeu</mot>
            <mot>manger</mot>
            <mot>voir</mot>
            <mot>dormir</mot>
            <mot>mot</mot>
            <mot>verbe</mot>
            <mot>sujet</mot>
        </niveau>
        <niveau niv='2'>
            <mot>doigt</mot>
            <mot>tigre</mot>
            <mot>gagner</mot>
            <mot>oncle</mot>
            <mot>tante</mot>
            <mot>langue</mot>
            <mot>plateau</mot>
            <mot>écran</mot>
            <mot>souris</mot>
            <mot>clavier</mot>
            <mot>flèche</mot>
        </niveau>
        <niveau niv='3'>
            <mot>tableau</mot>
            <mot>échalotte</mot>
            <mot>brise</mot>
            <mot>calcium</mot>
            <mot>vitamine</mot>
            <mot>complément</mot>
            <mot>modifier</mot>
            <mot>arc-en-ciel</mot>
            <mot>accuser</mot>
            <mot>ardente</mot>
            <mot>absente</mot>
        </niveau>
        <niveau niv='4'>
            <mot>inhibes</mot>
            <mot>inhumer</mot>
            <mot>insérer</mot>
            <mot>jouxter</mot>
            <mot>religion</mot>
            <mot>éléphant</mot>
            <mot>louange</mot>
            <mot>litrons</mot>
            <mot>lustrer</mot>
            <mot>maximum</mot>
            <mot>minimum</mot>
        </niveau>
        <niveau niv='5'>
            <mot>parallèle</mot>
            <mot>parallèlogramme</mot>
            <mot>parallèlisme</mot>
            <mot>trapéze</mot>
            <mot>scrutai</mot>
            <mot>orthographe</mot>
            <mot>grammaire</mot>
            <mot>conjugaison</mot>
            <mot>production</mot>
            <mot>tabasco</mot>
            <mot>ponctuation</mot>
        </niveau>
    </niveaux>   
</dictionnaire>
